### ISSUE TITLE
Examples will not work

### ISSUE THREAD

**Issue by manveru** [kinxer/crgeojson#7]
The examples won't work unless I use:

```
include GeoJSON
include GeoJSON::Coordinates
```

Error without this:

```
In lib/geojson/src/geojson/geometry/pseudo_geometry.cr:42:22

 42 | contents = CoordinateTree.new parser
                 ^-------------
Error: undefined constant CoordinateTree
```

The bigger problem is that the includes have to be at the top-level, and I'd rather not have it mixed into my whole environment.

**Comment by RespiteSage** [comment]
I've not had time yet to test this, but my inclination is that I probably missed a `require` or `include` somewhere. I'll try to look into it soon.

**Comment by RespiteSage** [comment]
@manveru Please take a look at the pull request if you get a chance. This is my first open-source project that I've released, and I want to learn as much as possible about both designing/improving a library interface and managing an open-source project.
